name: Build and Push Docker Image

on:
  push:
    tags:
      - "*"

env:
  GITHUB_REGISTRY: ghcr.io
  DOCKER_REGISTRY: thrysoee

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Lowercase repo name
        run: |
          echo "GITHUB_REPOSITORY_LOWERCASE=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
          echo "GITHUB_REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}"     >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.GITHUB_REGISTRY }}/${{ env.GITHUB_REPOSITORY_LOWERCASE }}/${{ env.GITHUB_REPOSITORY_NAME }}:${{ github.ref_name }}
            ${{ env.GITHUB_REGISTRY }}/${{ env.GITHUB_REPOSITORY_LOWERCASE }}/${{ env.GITHUB_REPOSITORY_NAME }}:latest
            ${{ env.DOCKER_REGISTRY }}/${{ env.GITHUB_REPOSITORY_NAME }}:${{github.ref_name}}
            ${{ env.DOCKER_REGISTRY }}/${{ env.GITHUB_REPOSITORY_NAME }}:latest

